### PR TITLE
Remove Duplicates from an array

### PR DESCRIPTION
**Pull request by subashpaul**

### CODE REVIEW

**Review by DevTMK — CHANGES_REQUESTED** [review]
Remove getDiffDays.md from this PR, it's not needed here

**Comment by subashpaul** [comment]
> Remove getDiffDays.md from this PR, it's not needed here

Done

**Comment by DevTMK** [comment]
No mate, you're not supposed to delete the file, just remove it from the commit

💡 You can refer [here](https://stackoverflow.com/a/46571620) for details

**Comment by DevTMK** [comment]
Closing this PR for now, Thanks

**Pull request closed without merging**
