### PR TITLE
Create array shuffle.cpp

### PR DESCRIPTION
**Pull request by void-57**

### CODE REVIEW

**Review by DevTMK — CHANGES_REQUESTED** [review]
Hey @void-57 , use template.md file to create new snip
And take a look at [contributing guidelines](https://github.com/DevTMK/snips/blob/9661c2f0362c46d8383ef5a5a18f0a557052dfde/CONTRIBUTING.md).

**Comment by void-57** [comment]
@DevTMK  What is result in template.md?

**Comment by DevTMK** [comment]
To show what the end result will look like if someone uses the snip 

E.g. - 
In this case, to show how the shuffle arrays snip will work:
Let's say we call the shuffle function: `shuffle([1, 2, 3, 4])` then it will return something like - `[2, 4, 3, 1]`, so the Result...
`shuffle([1, 2, 3, 4]); // [2, 4, 3, 1]`

**Comment by void-57** [comment]
Ok thank you

**Comment by void-57** [comment]
Please take a look I have contributed again @DevTMK

**Pull request closed without merging**
